package apispec

import "strings"

func SkillMarkdown(cfg Config) string {
	baseURL := normalizedBaseURL(cfg.BaseURL)
	expectedMX := strings.TrimRight(firstNonEmpty(cfg.ExpectedMX, "mail.example.com"), ".")
	docsURL := baseURL + "/api/docs.md"
	lines := []string{
		"---",
		"name: hlool-mail-api",
		"description: 使用 HLOOL Mail 创建临时邮箱、验证私有域名、通过 API 收信、读取验证码邮件并标记已读。适用于用户要求 AI 助手自动化临时邮箱、自定义域名收信、验证码获取或 HLOOL Mail API 流程。",
		"---",
		"",
		"# HLOOL Mail API Skill",
		"",
		"使用这个 Skill 通过已文档化的公开 API 操作 HLOOL Mail。HLOOL Mail 是开源且可自部署的项目，Base URL 应来自用户自己的实例；不要假设存在固定官方 API 域名。API 参考位于 `" + docsURL + "`，OpenAPI 文档位于 `" + baseURL + "/api/openapi.json`。",
		"",
		"## 基本规则",
		"",
		"- 受保护的 API Key 自动化调用使用 `X-API-Key`。",
		"- 不要反向分析网站、猜测隐藏端点、抓取控制台或发明参数。",
		"- 这是一份 API Key 自动化指南。登录、API Key 创建、域名管理、MX 检查、管理后台和用户管理都属于 Web Console 任务。",
		"- `POST /api/generate-email` 传入 `share: true` 可创建带 key 的邮箱分享；分享链接管理仍是 Web Console `cookie/session` 端点。",
		"- Webhook 管理操作是 Web Console `cookie/session` 端点，不属于 API Key 自动化。",
		"- 调用受保护端点前，先向用户索要 HLOOL Mail Base URL 和 API Key。",
		"- 如果用户没有明确给出完整邮箱或指定域名，先调用 `GET /api/domains/available` 获取可选域名。",
		"- 域名选择以 `data.public_domains` 和 `data.private_domains` 为准；`data.domains` 只是旧客户端公共域名 fallback。",
		"- 将公共域名和私有域名分组展示给用户。需要多个邮箱或多个域名处理时，支持多选后再逐个生成邮箱。",
		"- 不要在 `data.private_domains` 已包含可访问私有域名时要求用户手填私有域名。",
		"- 域名创建、MX 验证和 API Key 创建由用户在 Web Console 中完成。",
		"- 需要精确响应字段或示例时，先读取 `" + docsURL + "`。",
		"",
		"## 私有域名流程",
		"",
		"1. 先调用 `GET /api/domains/available`。如果 `data.private_domains` 已列出目标域名，直接让用户选择该域名。",
		"2. 如果目标域名不在 `data.private_domains` 中，让用户在 Web Console 中添加自己的域名。",
		"3. 让用户把域名 MX 记录指向 `" + expectedMX + "`。",
		"4. 对于 `user@example.com` 这类根域邮箱，根域 MX 记录就够了。",
		"5. 对于 `user@abc.example.com` 这类子域邮箱，还要让用户添加通配 MX 记录。",
		"6. 用户在 Web Console 中完成 MX 验证后，用目标域名调用 `POST /api/generate-email`。",
		"7. 只有当响应返回同一域名下的邮箱地址时，才视为私有域名设置成功。",
		"",
		"## 公共域名流程",
		"",
		"1. 带 `X-API-Key` 调用 `GET /api/domains/available`，从 `data.public_domains` 获取可用公共域名及元数据。",
		"2. 同时读取 `data.private_domains`，把当前 API Key 已可访问的私有域名作为同一组候选项展示。",
		"3. `data.domains` 只包含公共域名字符串，只有兼容旧客户端时才使用。",
		"4. 不传 domain 调用 `POST /api/generate-email` 可生成随机公共域名邮箱；更推荐显式传入用户从候选列表中选择的域名。",
		"5. 如果用户需要可分享收件箱，传入 `share: true` 并提供 `data.share.access_url`；移除 `#key=...` 后会进入手动输入 key 的页面。完整 token/key 只返回一次，不能再次查看旧链接。",
		"6. 如果目标网站拒绝该地址或没有邮件到达，建议换公共域名、换邮箱前缀、稍等片刻，或改用用户自己的私有域名。",
		"",
		"## 读取验证码邮件",
		"",
		"1. 每 3 秒调用一次 `GET /api/emails/next?email=MAILBOX`，最多等待 120 秒。",
		"2. 如果 `has_email=false`，说明还没有未读邮件到达；等待后继续轮询。",
		"3. 如果 `has_email=true`，从 `message.subject`、`message.text_content` 或已清洗的 `message.html_content` 中提取验证码。",
		"4. 匹配成功后停止轮询。该端点会自动将返回邮件标记为已读。",
		"5. 仅做人工检查时，使用 `GET /api/emails?email=MAILBOX&page=1&per_page=20`、`GET /api/email/:id` 和 `PATCH /api/email/:id/read`。",
		"6. 旧版 `limit` 形式会在 `data` 中返回数组；`page/per_page` 形式返回 `{items,page,per_page,total,total_pages}`。",
		"",
		"## 核心端点",
		"",
	}
	for _, op := range AutomationOperations() {
		lines = append(lines, "- `"+op.Method+" "+op.DisplayPath()+"` - "+op.Summary+".")
	}
	lines = append(lines,
		"",
		"## 最小请求模式",
		"",
		"先发现可用域名：",
		"",
		"```bash",
		"curl \""+baseURL+"/api/domains/available\" \\",
		"  -H \"X-API-Key: YOUR_KEY\"",
		"```",
		"",
		"再使用用户选择的域名生成邮箱：",
		"",
		"```bash",
		"curl -X POST \""+baseURL+"/api/generate-email\" \\",
		"  -H \"Content-Type: application/json\" \\",
		"  -H \"X-API-Key: YOUR_KEY\" \\",
		"  -d '{\"prefix\":\"verify\",\"domain\":\"example.com\",\"share\":false}'",
		"```",
		"",
		"```bash",
		"curl \""+baseURL+"/api/emails?email=verify@example.com&page=1&per_page=20\" \\",
		"  -H \"X-API-Key: YOUR_KEY\"",
		"```",
		"",
		"```bash",
		"curl \""+baseURL+"/api/emails/next?email=verify@example.com\" \\",
		"  -H \"X-API-Key: YOUR_KEY\"",
		"```",
		"",
		"## 响应处理",
		"",
		"响应是带有 `success`、`data` 和 `error` 的 JSON 信封。API Key 调用还可能包含 `usage`。如果 `success` 为 false，把 `error` 当作可能已本地化的人类可读文本，报告给用户并建议最可能的下一步。自动化控制流程应依赖 HTTP 状态码和 `success`，不要依赖精确 `error` 字符串。",
		"",
	)
	return strings.Join(lines, "\n")
}
